services:
  - type: web
    name: pwj-personal-wine-journal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --chdir . --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
